USE topclass_schedr;

CREATE TABLE REF_SUBJECTS(
	SUBJECT_CODE INT PRIMARY KEY NOT NULL,
    SUBJECT_NAME VARCHAR(255),
    SUBJECT_DESCRIPTION TEXT
);

CREATE TABLE STUDENTS(
	STUDENT_ID INT PRIMARY KEY NOT NULL,
    YEAR_OF_GRADUATION DATE,
    OTHER_DETAILS TEXT
);

CREATE TABLE REF_GENDER(
	GENDER_MFU INT PRIMARY KEY NOT NULL,
    GENDER_DESCRIPTION CHAR
);

CREATE TABLE ADDRESSES(
	ADDRESS_ID INT PRIMARY KEY NOT NULL,
    STREET_ADDRESS1 VARCHAR(255) NOT NULL,
    STREET_ADDRESS2 VARCHAR(255) NULL,
    CITY VARCHAR(255) NOT NULL,
    STATE VARCHAR(255) NULL,
	ZIP VARCHAR(255) NULL,
    OTHER_DETAILS TEXT
);

CREATE TABLE INSTRUCTORS(
	INSTRUCTOR_ID INT PRIMARY KEY NOT NULL,
    QUALIFICATIONS VARCHAR(255),
    OTHER_DETAILS TEXT
);

CREATE TABLE REF_SCORE_STATUS(
	STATUS_CODE INT PRIMARY KEY NOT NULL,
    STATUS_DESCRIPTION TEXT
);

CREATE TABLE REF_RETEST_STATUS_CODES(
	RETEST_STATUS INT PRIMARY KEY NOT NULL,
    RETEST_STATUS_DESCRIPTION TEXT
);

CREATE TABLE CLASSES(
	CLASS_ID INT PRIMARY KEY NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    NUMBER_OF_SEATS INT(4),
	OTHER_DETAILS TEXT,
    SUBJECT_CODE INT,
    FOREIGN KEY (SUBJECT_CODE) REFERENCES REF_SUBJECTS(SUBJECT_CODE)
);

CREATE TABLE STUDENT_CLASSES(
	SUBJECT_CLASS_ID INT PRIMARY KEY NOT NULL,
    ATTENDANCE_FROM_DATE DATE,
    ATTENDANCE_TO_DATE DATE,
    KNOWLEDGE_SCORE VARCHAR(255),
    RETEST_SCORE VARCHAR(255),
    SKILL_SCORE VARCHAR(255),
    OTHER_DETAILS TEXT,
    CLASS_ID INT,
    FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID),
    RETEST_STATUS INT,
    FOREIGN KEY (RETEST_STATUS) REFERENCES REF_RETEST_STATUS_CODES(RETEST_STATUS),
    STATUS_CODE INT,
    FOREIGN KEY (STATUS_CODE) REFERENCES REF_SCORE_STATUS(STATUS_CODE),
    STUDENT_ID INT,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID)
);

CREATE TABLE INSTRUCTORS_CLASSES(
	CLASS_ID INT NOT NULL,
    FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID),
    INSTRUCTOR_ID INT NOT NULL,
    FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTORS(INSTRUCTOR_ID)
);

CREATE TABLE PEOPLE(
	PERSON_ID INT PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    MIDDLE_NAME VARCHAR(255) NULL,
    LAST_NAME VARCHAR(255) NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    HOME_PHONE VARCHAR(255) NULL,
    CELL_PHONE VARCHAR(255) NULL,
    EMAIL_ADDRESS VARCHAR(255) NULL,
    OTHER_DETAILS TEXT,
    ADDRESS_ID INT,
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESSES(ADDRESS_ID),
    GENDER_MFU INT,
    FOREIGN KEY (GENDER_MFU) REFERENCES REF_GENDER(GENDER_MFU),
    STUDENT_ID INT,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID)
);
